<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ModulesFootersPage;
use Fisharebest\Webtrees\I18N;

$groups[''] = [];
foreach($favorites as $favorite) {
  $groups[$favorite['group']] = [
    $favorite['type'] => $favorite,
    'id' => $favorite['favorite_id'],
  ];
}

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ModulesFootersPage::class) => I18N::translate('Footers'), $title]]) ?>

<h1><?= $title ?></h1>

<form  method="post">
  <?= csrf_field() ?>
  <label><?= I18N::translate('Make any changes and then click') ?></label> 
  <input type="submit" value="<?= I18N::translate('Save') ?>"><br>

  <h3><?php echo I18N::translate('Groups') ?></h3>
  <input type="radio" name="active_group" value="0" <?php if (!$default_group) echo 'checked'; ?> >
  <input type="text" name="rename_default" value="" size="60" placeholder="[ ] <?= I18N::translate('Rename the default group') ?>">
    <br>
  <?php foreach ($groups as $group => $item) { ?>
    <?php if ($group) { ?>
      <input type="radio" name="active_group" value="<?= $item['id'] ?>" <?php if ($group == $default_group) echo 'checked'; ?> >
      <input type="text" name="group[<?= $item['id'] ?>]" value="<?= htmlspecialchars($group) ?>" size="60"><br>
    <?php } ?>
  <?php } ?>

  <?php if (isset($groups[$default_group])) { ?>
    <input type="radio" name="active_group" value="-1">
    <input type="text" name="default_group" value="" size="60" placeholder="<?php echo I18N::translate('Enter new group') ?>">
    <input type="hidden" name="new_group" value="1">
  <?php } else { ?>
    <input type="radio" name="active_group" value="-1" checked>
    <input type="text" name="default_group" value="<?= htmlspecialchars($default_group) ?>" size="60">
    <input type="hidden" name="new_group" value="0">
  <?php } ?>
  <br>
</form>
<br>
<?php if(isset($debug)) echo htmlspecialchars(print_r($debug,true)); ?>

