<?php

return [    
    'Favorite' => 'Favoriten',
    'Favorites Menu' => 'Favoriten Menü',
    'Manage favorites based on current page.' => 'Verwalte die Favoriten basierend auf der aktuellen Seite.',
    'Favorite moved to group: ' => 'Favorit verschoben in Gruppe: ',
    'Remove favorite' => 'Seite aus Favoriten entfernen',
    'Add favorite' => 'Seite zu Favoriten hinzufügen',
    'Move from' => 'Verschiebe von',
    'Null xref for %s' => 'Kein xref für %s',
    'Invalid type' => 'ungültige Type',
    'Missing' => 'Fehlt',
    'Bad tree' => 'Baum Fehler',
    'Imported %s item(s). %s duplicates. %s error(s)' => '%s Teile importiert. %s Doppelte. %s Fehler',
    'Added' => 'Hinzugefügt',
    'Duplicates' => 'Doppelte',
    'Errors' => 'Fehler',
    'Nothing to import' => 'Nichts zu importieren',
    'Updated URL links' => 'URLs aktualisiert',
    'Deleted %s favorite(s).' => '%s Favoriten gelöscht.',
    '%s moved to [%s]' => '%s verschoben nach [%s]',
    'Moved %s favorite(s).' => '%s Favoriten verschoben.',
    'Settings saved.' => 'Einstellungen gespeichert',
    'Show no secondary menu' => 'Keine zweite Gruppe zeigen',
    'Yours' => 'Deine',
    
    'Favorites Menu Settings' => 'Einstellungen für das Favoriten Menü',
    'Make any changes and then click' => 'Ändere etwas und dann klicke',
    'Save' => 'Speichern',
    'Groups' => 'Gruppen',
    'Shared' => 'Gemeinsam',
    'Default' => 'Standardgruppe',
    'Group' => 'Gruppenname',
    'favorite(s)' => 'Favorite(n)',
    'Rename the default group' => '', // Neuen Gruppennamen erstellen
    'Enter new group' => 'Neue Gruppe hinzufügen',
    'Secondary Menu Groups' => 'Zweite Gruppe',
    'Additional groups are listed after default group. They can include groups shared by other users.' => 'Die ausgewählte Gruppe wird zusätzlich zur Standardgruppe im Menü angezeigt.',
    'Move' => 'Verschieben',
    'Remove' => 'Entfernen',
    'Move to' => 'Verschieben in',
    'Add new link.' => 'Zur Gruppe hinzufügen',
    'Text' => 'Menütitel',
    'URL' => 'Internetadresse',
    'Internetadresse (URL)' => 'URL', // how to translate this
    
    'Import/Export' => 'Im- und Export',
    'To export your favorites click' => 'Zum "Speichern" hier klicken',
    'Export' => 'Speichern',
    'To import your favorites, paste the contents of an export .CSV file below and  click' => 'Zum Einlesen den Inhalt der exportierten csv-Datei einfügen und "Einlesen" klicken',
    'Import' => 'Einlesen',
    'The columns are:' => 'Die Spalten sind:',
    'Duplicate or invalid entries are ignored.' => 'Doppelte oder ungültige Einträge werden ignoriert.',
    
    'Control panel' => 'Einstellungen',
    'Footers' => 'Fußzeilen',
];
