<?php

return [
    'Favorite' => 'Favori',
    'Favorites Menu' => 'Menu des favoris',
    'Manage favorites based on current page.' => 'Gérer les favoris en fonction de la page actuelle.',
    'Favorite moved to group: ' => 'Le favori a été déplacé vers le groupe : ',
    'Remove favorite' => 'Supprimer des favoris',
    'Add favorite' => 'Ajouter aux favoris',
    'Move from' => 'Déplacer depuis',
    'Null xref for %s' => 'Aucune référence croisée pour %s',
    'Invalid type' => 'Type invalide',
    'Missing' => 'Manquant',
    'Bad tree' => 'Arborescence invalide',
    'Imported %s item(s). %s duplicates. %s error(s)' => '%s élément(s) importé(s). %s doublon(s). %s erreur(s).',
    'Added' => 'Ajouté',
    'Duplicates' => 'Doublons',
    'Errors' => 'Erreurs',
    'Nothing to import' => 'Rien à importer',
    'Updated URL links' => 'Liens URL mis à jour',
    'Deleted %s favorite(s).' => '%s favori(s) supprimé(s).',
    '%s moved to [%s]' => '%s déplacé vers [%s]',
    'Moved %s favorite(s).' => '%s favori(s) déplacé(s).',
    'Settings saved.' => 'Paramètres enregistrés.',
    'Show no secondary menu' => 'Ne pas afficher de menu secondaire',
    'Yours' => 'Les vôtres',

    'Favorites Menu Settings' => 'Paramètres du menu des favoris',
    'Make any changes and then click' => 'Effectuez des modifications puis cliquez sur',
    'Save' => 'Enregistrer',
    'Groups' => 'Groupes',
    'Shared' => 'Partagés',
    'Default' => 'Groupe par défaut',
    'Group' => 'Groupe',
    'favorite(s)' => 'favori(s)',
    'Rename the default group' => 'Renommer le groupe par défaut',
    'Enter new group' => 'Saisir un nouveau groupe',
    'Secondary Menu Groups' => 'Groupes du menu secondaire',
    'Additional groups are listed after default group. They can include groups shared by other users.'
        => 'Les groupes supplémentaires sont affichés après le groupe par défaut. Ils peuvent inclure des groupes partagés par d’autres utilisateurs.',
    'Move' => 'Déplacer',
    'Remove' => 'Supprimer',
    'Move to' => 'Déplacer vers',
    'Add new link.' => 'Ajouter un nouveau lien.',
    'Text' => 'Texte',
    'URL' => 'URL',
    'Internetadresse (URL)' => 'Adresse internet (URL)',

    'Import/Export' => 'Import / Export',
    'To export your favorites click' => 'Pour exporter vos favoris, cliquez sur',
    'Export' => 'Exporter',
    'To import your favorites, paste the contents of an export .CSV file below and click'
        => 'Pour importer vos favoris, collez ci-dessous le contenu d’un fichier CSV exporté puis cliquez sur',
    'Import' => 'Importer',
    'The columns are:' => 'Les colonnes sont :',
    'Duplicate or invalid entries are ignored.' => 'Les entrées dupliquées ou invalides sont ignorées.',

    'Control panel' => 'Panneau de configuration',
    'Footers' => 'Pieds de page',
];