<?php

return [
			
			'Favorite' => 'Favorieten',
			'Favorites Menu' => 'Favorietenmenu',
			'Manage favorites based on current page.' => 'Favorieten beheren op basis van huidige pagina.',
			'Favorite moved to group: ' => 'Favoriet verplaatst naar groep: ',
			'Remove favorite' => 'Huidige pagina verwijderen uit favorieten',
			'Add favorite' => 'Huidige pagina toevoegen aan favorieten',
			'Move from' => 'Verplaatsen van',
			'Null xref for %s' => 'Geen xref voor %s',
			'Invalid type' => 'Ongeldig type',
			'Missing' => 'Ontbreekt',
			'Bad tree' => 'Fout in ongeldige boomstructuur',
			'Imported %s item(s). %s duplicates. %s error(s)' => '%s items geïmporteerd. %s duplicaten. %s fout(en)',
			'Added' => 'Toegevoegd',
			'Duplicates' => 'Duplicaten',
			'Errors' => 'Fouten',
			'Nothing to import' => 'Niets te importeren',
			'Updated URL links' => 'URL-links bijgewerkt',
			'Deleted %s favorite(s).' => '%s favorieten verwijderd.',
			'%s moved to [%s]' => '%s verplaatst naar [%s]',
			'Moved %s favorite(s).' => '%s favorieten verplaatst.',
			'Settings saved.' => 'Instellingen opgeslagen',
			'Yours' => 'Uw',
			
			'Favorites Menu Settings' => 'Instellingen favorietenmenu',
			'Make any changes and then click' => 'Breng wijzigingen aan en klik vervolgens op',
			'Save' => 'Opslaan',
			'Groups' => 'Groepen',
			'Shared' => 'Gedeeld',
			'Default' => 'Standaard',
			'Group' => 'Groep',
			'favorite(s)' => 'favoriet(en)',
			'Rename the default group' => 'Naam van de standaardgroep wijzigen',
			'Enter new group' => 'Nieuwe groep toevoegen',
			'Secondary Menu Groups' => 'Submenugroepen',
			'Additional groups are listed after default group. They can include groups shared by other users.' => 'Andere groepen worden weergegeven na de standaardgroep. Dit kunnen groepen zijn die door andere gebruikers worden gedeeld.',
			'Show no secondary menu' => 'Geen submenu weergeven',
			'Move' => 'Verplaatsen',
			'Remove' => 'Verwijderen',
			'Move to' => 'Verplaatsen naar',
			'Add new link.' => 'Nieuwe link toevoegen.',
			'Text' => 'Tekst',
			'URL' => 'URL',
			'Internetadresse (URL)' => 'Internetadres (URL)',

			'Import/Export' => 'Importeren/Exporteren',
			'To export your favorites click' => 'Om uw favorieten te exporteren, klik op',
			'Export' => 'Exporteren',
			'To import your favorites, paste the contents of an export .CSV file below and  click' => 'Om uw favorieten te importeren, plak hieronder de inhoud van een geëxporteerd CSV-bestand en klik op',
			'Import' => 'Importeren',
			'The columns are:' => 'De kolomnamen zijn:',
			'Duplicate or invalid entries are ignored.' => 'Dubbele of ongeldige vermeldingen worden genegeerd.',
			
			'Control panel' => 'Configuratiescherm',
			'Footers' => 'Voetteksten',
];
